Moesif/moesif-servlet

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifConfiguration.java, moesif-servlet/src/main/java/com/moesif/servlet/MoesifConfigurationAdapter.java, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet/src/main/java/com/moesif/servlet/wrappers/LoggingHttpServletRequestWrapper.java
Add: Transaction Id to Request-Response Headers
Update: moesifapi dependnecy to 1.5.0
Bump version to 1.3.0
=> Add: Transaction Id to Request-Response Headers

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java
Add: Dynamically configure sampling events
Bump version to 1.4.0
=> Add: Dynamically configure sampling events

README.md, jersey-servlet-example/pom.xml, jersey-servlet-example/src/main/webapp/WEB-INF/web.xml, servlet-example/pom.xml, servlet-example/src/main/webapp/WEB-INF/web.xml, spark-servlet-example/pom.xml, spark-servlet-example/src/main/webapp/WEB-INF/web.xml, spring-example/pom.xml, spring-example/src/main/java/com/moesif/servlet/spring/MyConfig.java, spring-mvc-example/pom.xml, spring-mvc-example/src/main/java/com/moesif/servlet/spring/example/hello/web/HelloController.java, spring-mvc-example/src/main/resources/logback.xml, spring-mvc-example/src/main/webapp/WEB-INF/appconfig-mvc.xml, spring-mvc-example/src/main/webapp/WEB-INF/appconfig-root.xml, spring-mvc-example/src/main/webapp/WEB-INF/views/hello.jsp, spring-mvc-example/src/main/webapp/WEB-INF/web.xml, spring-mvc-example/src/main/webapp/resources/css/bootstrap.min.css, spring-mvc-example/src/main/webapp/resources/js/bootstrap.min.js
Add: Spring MVC Example
Upate: README.md
Update: Dependency in examples
=> Add: Spring MVC Example

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet/src/test/java/com/moesif/servlet/MoesifServletTests.java
Add: Unit Test
Add: updateUser function
Refactor: moesifapi dependency to 1.6.1
Bump version to 1.5.2
=> Add: Unit Test

jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-example/pom.xml, spring-mvc-example/pom.xml
Refactor: Update Moesif Servlet dependencies
=> Refactor: Update Moesif Servlet dependencies

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet/src/test/java/com/moesif/servlet/MoesifServletTests.java
Add: UpdateCompany and UpdateCompaniesBatch function
Add: UpdateCompany and UpdateCompaniesBatch tests
Update: REAMDE.md
Bump version to 1.5.3
=> Add: UpdateCompany and UpdateCompaniesBatch function

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifConfiguration.java, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-springrequest/README.md, moesif-springrequest/pom.xml, moesif-springrequest/src/main/java/com/moesif/springrequest/MoesifRequestConfiguration.java, moesif-springrequest/src/main/java/com/moesif/springrequest/MoesifSpringRequestInterceptor.java, springrequest-example/pom.xml, springrequest-example/src/main/java/com/moesif/springrequestexample/RequestConfig.java
Add: CompanyId to the EventModel
Add: IdentifyCompany and outgoing API calls configuration option
Update: moesifapi dependency to 1.6.3
Update: REAMDE.md
Update: Dependencies and configuration options in sprintrequest-example
Bump moesif-servlet version to 1.5.4
Bump moesif-springrequest version to 1.0.2
=> Add: CompanyId to the EventModel

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-springrequest/README.md, moesif-springrequest/pom.xml, moesif-springrequest/src/main/java/com/moesif/springrequest/MoesifRequestConfiguration.java, moesif-springrequest/src/main/java/com/moesif/springrequest/MoesifSpringRequestInterceptor.java
Add: LogBody configuration option to remove request and response body
Bump moesif-servlet version to 1.5.5
Bump moesif-springrequest version to 1.0.3
=> Add: LogBody configuration option to remove request and response body

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java
Add: Setter method for logBody configuration option
Bump version to 1.5.6
=> Add: Setter method for logBody configuration option

README.md, servlet-example/README.md, servlet-example/pom.xml, servlet-example/src/main/webapp/WEB-INF/web.xml, spark-servlet-example/README.md, spark-servlet-example/pom.xml, spark-servlet-example/src/main/webapp/WEB-INF/web.xml, spring-example/README.md, spring-example/pom.xml, spring-example/src/main/java/com/moesif/servlet/spring/MyConfig.java, spring-mvc-example/README.md, spring-mvc-example/pom.xml, spring-mvc-example/src/main/webapp/WEB-INF/web.xml
Bump moesif-servlet and moesifapi dependencies
=> Bump moesif-servlet and moesifapi dependencies

jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-example/pom.xml, spring-mvc-example/pom.xml, springrequest-example/pom.xml
Bump: moesif-servlet dependency to 1.5.9
=> Bump: moesif-servlet dependency to 1.5.9

jersey-servlet-example/README.md, jersey-servlet-example/pom.xml, servlet-example/README.md, servlet-example/pom.xml, spark-servlet-example/README.md, spark-servlet-example/pom.xml, spring-example/README.md, spring-example/pom.xml, springrequest-example/pom.xml, springrequest-example/src/main/java/com/moesif/springrequestexample/RequestConfig.java
=> Bump moesif-servlet to 1.6.3

README.md, moesif-servlet/pom.xml, moesif-servlet/src/test/java/com/moesif/servlet/MoesifServletTests.java
Add: Campaign object to Update user and company tests
Refactor: Update moesifapi version to 1.6.7
Bump version to 1.6.7
=> Add: Campaign object to Update user and company tests

jersey-servlet-example/pom.xml, moesif-springrequest/README.md, moesif-springrequest/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-starter-example/pom.xml, spring-boot-starter-example/src/main/java/com/moesif/servlet/spring/MyConfig.java
Refactor: Bump moesif-api dependency to 1.6.7 for moesif-springrequest
Refactor: Bump moesif-springrequest version to 1.0.7
Refactor: Update moesif-servlet dependency to 1.6.7 for examples
=> Refactor: Bump moesif-api dependency to 1.6.7 for moesif-springrequest

spring-boot-servlet-example/pom.xml, spring-boot-servlet-example/src/main/java/com/moesif/servlet/spring/MyConfig.java, springrequest-example/pom.xml
Refactor: Bump moesif-springrequest dependency to 1.0.7
Refactor: Bump moesif-servlet dependency to 1.6.7
=> Refactor: Bump moesif-springrequest dependency to 1.0.7

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-springrequest/README.md, moesif-springrequest/pom.xml, moesif-springrequest/src/main/java/com/moesif/springrequest/MoesifSpringRequestInterceptor.java
Add: direction field to specify incoming or outgoing API call
Refactor: Bump moesifapi version to 1.6.8
Bump moesif-servlet version to 1.6.8
Bump moesif-springrequest to 1.0.8
=> Add: direction field to specify incoming or outgoing API call

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-springrequest/README.md, moesif-springrequest/pom.xml, moesif-springrequest/src/main/java/com/moesif/springrequest/MoesifSpringRequestInterceptor.java
Add: Weight field to event model
Refactor: Bump moesifapi version to 1.6.9
Bump moesif-servlet version to 1.6.9
Bump moesif-springrequest to 1.0.9
=> Add: Weight field to event model

jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-starter-example/pom.xml, springrequest-example/pom.xml
Refactor: Bump moesif-servlet dependency to 1.6.9
Refactor: Bump moesif-springrequest dependency to 1.0.9
=> Refactor: Bump moesif-servlet dependency to 1.6.9

jersey-servlet-example/src/main/java/com/moesif/servlet/jersey/example/CompaniesServlet.java, jersey-servlet-example/src/main/java/com/moesif/servlet/jersey/example/JerseyDemo.java, jersey-servlet-example/src/main/java/com/moesif/servlet/jersey/example/UsersServlet.java, jersey-servlet-example/src/main/webapp/WEB-INF/web.xml, servlet-example/src/main/java/com/moesif/servlet/example/CompaniesServlet.java, servlet-example/src/main/java/com/moesif/servlet/example/ServletDemo.java, servlet-example/src/main/java/com/moesif/servlet/example/UsersServlet.java, servlet-example/src/main/webapp/WEB-INF/web.xml, spark-servlet-example/src/main/java/com/moesif/servlet/spark/example/SparkDemo.java, spring-boot-servlet-example/src/main/java/com/moesif/servlet/spring/ApiController.java, spring-boot-servlet-example/src/main/java/com/moesif/servlet/spring/MyConfig.java, spring-boot-starter-example/src/main/java/com/moesif/servlet/spring/ApiController.java, spring-boot-starter-example/src/main/java/com/moesif/servlet/spring/MyConfig.java, springrequest-example/src/main/java/com/moesif/springrequestexample/MoesifHttpClient.java, springrequest-example/src/main/java/com/moesif/springrequestexample/PostController.java
Add: Endpoint to update User and company in examples
=> Add: Endpoint to update User and company in examples

README.md, jersey-servlet-example/pom.xml, moesif-servlet/pom.xml, moesif-springrequest/README.md, moesif-springrequest/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-starter-example/pom.xml
Creating fully automated CI/CD deployment `Azure Artifacts` repos and to `Sonatype Nexus maven central (repo.maven.apache.org)` using `Azure Devops` Release.
* updated pom.xml files
* Fixed Spring framework broken links and few libs with CVE.
=> Publish to Azure Artifacts and Sonatype nexus mavencentral repos

spark-servlet-example/README.md, spring-boot-starter-example/README.md, springrequest-example/pom.xml
Bringing few examples up to date. Also, removing unnecessary repos (bintray and springboot)
=> Fix examples spark-servlet, spring-boot, springrequest. removing bintray/other repos.

README.md, moesif-servlet/pom.xml, moesif-springrequest/README.md, moesif-springrequest/pom.xml
Log4j for CVE-2021-44228
Bump: moesif-servlet to 1.6.13
Bump: moesif-springrequest to 1.0.12
=> Log4j for CVE-2021-44228

jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-servlet-example/src/main/java/com/moesif/servlet/spring/Application.java, spring-boot-starter-example/pom.xml, springrequest-example/pom.xml
Refactor: Bump moesif-servlet version to 1.6.13 in examples
Refactor: Bump moesif-springrequest version to 1.0.12 in examples
Refactor: Bump Spring Boot and Spring Framework to latest version
=> Refactor: Bump moesif-servlet version to 1.6.13 in examples

README.md, moesif-servlet/pom.xml, moesif-springrequest/README.md, moesif-springrequest/pom.xml
Update log4j CVE-2021-45046
Bump: moesif-servlet to 1.6.14
Bump: moesif-springrequest to 1.0.13
=> Update log4j CVE-2021-45046

README.md, jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-starter-example/pom.xml, springrequest-example/pom.xml
Refactor: Bump moesif-servlet to 1.6.15
Refactor: Bump moesif-springrequest to 1.0.13
Refactor: Bump example version
=> Refactor: Bump moesif-servlet to 1.6.15

README.md, moesif-servlet/pom.xml, moesif-springrequest/README.md, moesif-springrequest/pom.xml
Log4j for CVE-2021-45105
Bump: moesif-servlet to 1.6.16
Bump: moesif-springrequest to 1.0.14
=> Log4j for CVE-2021-45105

jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-starter-example/pom.xml, springrequest-example/pom.xml
Refactor: Bump moesif-servlet to 1.6.16
Refactor: Bump moesif-springrequest to 1.0.16
Refactor: Bump example version
=> Refactor: Bump moesif-servlet to 1.6.16

README.md, jersey-servlet-example/pom.xml, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/AppConfigManager.java, moesif-servlet/src/main/java/com/moesif/servlet/BatchProcessor.java, moesif-servlet/src/main/java/com/moesif/servlet/MoesifConfiguration.java, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet/src/test/java/com/moesif/servlet/MoesifServletTests.java, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-starter-example/pom.xml
1. Added a new class BatchProcessor to manage queue and periodic taskRunner to send events in batches to moesif.
2. Added two timer tasks for repeated fixed delay execution. One tasks pulls app config periodically from the server and update the local cache. Second tasks runs the batch processor's method periodically to send the events to the server.
3. Added sanity in add batch event to check liveness of the task-runner. If batch event taskRunner is not active then restart it.
4. Did few refactoring to isolate the functionality based on name of the methods.
5. Bumped up the version of the servlet to 1.6.17 and updated the other affected README & repos.
Ticket link: https://www.pivotaltracker.com/n/projects/1646401/stories/172421968
=> Queuing and batching support in java servlet.

moesif-servlet/src/main/java/com/moesif/servlet/BatchProcessor.java
Ensure matching on correct TimeoutException;
=> Fix: Use import java.util.concurrent.TimeoutException;

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet/src/test/java/com/moesif/servlet/MoesifServletTests.java
Refactor: Schedule trigger for AppConfig job every X seconds
Refactor: Fix Moesif-servlet tests
Refactor: Bump moesifapi to version 1.6.15
Refactor: README.md
Bump moesif-servlet 1.7.1
=> Refactor: Schedule trigger for AppConfig job every X seconds

README.md, moesif-servlet/pom.xml
Refactor: Bump moesifapi-java version to 1.6.16
Bump moesif-servlet version to 1.7.2
=> Refactor: Bump moesifapi-java version to 1.6.16

jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-starter-example/pom.xml
Refactor: Bump moesif-servlet version to 1.7.2 in examples
Refactor: Bump version in examples
=> Refactor: Bump moesif-servlet version to 1.7.2 in examples

examples/spring-boot-starter-example-jakarta/README.md, examples/spring-boot-starter-example-jakarta/pom.xml, examples/spring-boot-starter-example-jakarta/src/main/java/com/moesif/servlet/spring/ApiController.java, examples/spring-boot-starter-example-jakarta/src/main/java/com/moesif/servlet/spring/Application.java, examples/spring-boot-starter-example-jakarta/src/main/java/com/moesif/servlet/spring/Greeting.java, examples/spring-boot-starter-example-jakarta/src/main/java/com/moesif/servlet/spring/HtmlController.java, examples/spring-boot-starter-example-jakarta/src/main/java/com/moesif/servlet/spring/MyConfig.java, examples/spring-boot-starter-example-jakarta/src/main/webapp/WEB-INF/jsp/index.jsp, moesif-servlet-jakarta/pom.xml, moesif-servlet-jakarta/src/main/java/com/moesif/servlet/BatchProcessor.java, moesif-servlet-jakarta/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet-jakarta/src/test/java/com/moesif/servlet/MoesifServletTests.java
* Update dependencies for `moesif-servlet-jakarta` - removed unnecessary ones 
* Added example `spring-boot-starter-example-jakarta`
Works with `java 17` and `spring boot 3.0.0`
To address: https://github.com/Moesif/moesif-servlet/issues/98
#183987583
=> Add example, update dependencies moesif-servlet-jakarta

README.md, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/BatchProcessor.java, moesif-servlet/src/test/java/com/moesif/servlet/MoesifServletTests.java, moesif-springrequest/README.md, moesif-springrequest/pom.xml
No changes in core sdk functionality.
* Removing unnecessary/unused dependency on `jackson` in the sdks
* Updated other 3rd party dependencies, including fix to broken mockito.
* Updated README with fixes to instructions, and updated versions
This is core updates (part 1). After publishing to maven central, a new PR with updates to examples will complete the task
#184005245
=> moesif-servlet and moesif-springrequest - remove unused Jackson, update README

jersey-servlet-example/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spark-servlet-example/src/main/java/com/moesif/servlet/spark/example/SparkDemo.java, spring-boot-servlet-example/pom.xml, spring-boot-servlet-example/src/main/java/com/moesif/servlet/spring/MyConfig.java, spring-boot-starter-example/pom.xml, spring-boot-starter-example/src/main/java/com/moesif/servlet/spring/MyConfig.java, springrequest-example/pom.xml
* Update examples: bump dependencies versions, remove unused/unnecessary imports, updated deprecated calls
=> Update examples: Update jackson, Reduce/remove/update dependencies

jersey-servlet-example/pom.xml, moesif-servlet-jakarta/pom.xml, moesif-servlet/pom.xml, moesif-springrequest/pom.xml, servlet-example/pom.xml, spark-servlet-example/pom.xml, spring-boot-servlet-example/pom.xml, spring-boot-starter-example/pom.xml, springrequest-example/pom.xml
1. update moesif-servlet and servlet-example version dependency
=> #185690008 : update version

README.md, examples-jakarta/spring-boot-starter-example-tomcat/pom.xml, examples-jakarta/spring-boot-starter-example-tomcat/src/main/java/com/moesif/servlet/spring/ApiController.java, jersey-servlet-example/pom.xml, jersey-servlet-example/src/main/java/com/moesif/servlet/jersey/example/SubscriptionsServlet.java, moesif-servlet-jakarta/pom.xml, moesif-servlet-jakarta/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet-jakarta/src/test/java/com/moesif/servlet/MoesifServletTests.java, moesif-servlet/pom.xml, moesif-servlet/src/main/java/com/moesif/servlet/MoesifFilter.java, moesif-servlet/src/test/java/com/moesif/servlet/MoesifServletTests.java, moesif-springrequest/pom.xml, servlet-example/pom.xml, servlet-example/src/main/java/com/moesif/servlet/example/SubscriptionsServlet.java, spark-servlet-example/pom.xml, spark-servlet-example/src/main/java/com/moesif/servlet/spark/example/SparkDemo.java, spring-boot-servlet-example/pom.xml, spring-boot-servlet-example/src/main/java/com/moesif/servlet/spring/ApiController.java, spring-boot-starter-example/pom.xml, spring-boot-starter-example/src/main/java/com/moesif/servlet/spring/ApiController.java, springrequest-example/pom.xml, springrequest-example/src/main/java/com/moesif/springrequestexample/PostController.java
Still requires the latest java API release (with subscription support) to be added to POM of each project. Then, this will all need to be tested.
=> Added subscription support

spring-boot-servlet-example/pom.xml
Bumps org.apache.tomcat.embed:tomcat-embed-core from 8.5.93 to 8.5.99.
---
updated-dependencies:
- dependency-name: org.apache.tomcat.embed:tomcat-embed-core dependency-type: direct:production ...
=> Build(deps): Bump org.apache.tomcat.embed:tomcat-embed-core

moesif-servlet/pom.xml
revert last change to disable sign
=> Revert - disable sign

README.md, examples-jakarta/spring-boot-starter-example-tomcat/pom.xml, examples-jakarta/spring-boot-starter-example-undertow/pom.xml, moesif-servlet-jakarta/README.md, moesif-servlet-jakarta/pom.xml
=> Version Update
